sudo: required
services:
  - docker

before_install:
  - docker build -t nandrease/git-workflow -f Dockerfile.dev .

script:
  - docker run -e CI=true nandrease/git-workflow npm test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "git-workflow"
  env: "Gitworkflow-env"
  bucket_name: "elasticbeanstalk-us-east-2-568157342000"
  bucket_path: "git-workflow"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

