version: '3'
services:
  react-app:
    # image: frontend
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - CHOKIDAR_USEPOLLING=true # Makes hot-reloadind work for windows
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - CHOKIDAR_USEPOLLING=true # Makes hot-reloadind work for windows
    volumes:
      - /app/node_modules
      - .:/app
    command: [npm, test]

